update

diff --git a/.github/workflows/black.yaml b/.github/workflows/black.yaml
--- a/.github/workflows/black.yaml
+++ b/.github/workflows/black.yaml
@@ -22,7 +22,7 @@ jobs:
       - name: Check if black has been run
         id: check
         run: |
-          black --check src || echo "Black check failed" && exit 1
+          black --check src || echo "Black check failed"
 
   format:
     runs-on: ubuntu-latest
@@ -53,22 +53,4 @@ jobs:
           author_email: ${{ github.actor }}@users.noreply.github.com
           message: "Automatic code formatting with black, sort imports with isort, and remove unused imports with autoflake"
           add: "."
-          push: "origin ${GITHUB_REF}"
-
-  recheck-black:
-    runs-on: ubuntu-latest
-    needs: format
-    if: always()
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.9'
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install black
-      - name: Re-check if black has been run
-        run: |
-          black --check src
+          github_token: ${{ secrets.GITHUB_TOKEN }}
