new change to black

diff --git a/.github/workflows/black.yaml b/.github/workflows/black.yaml
--- a/.github/workflows/black.yaml
+++ b/.github/workflows/black.yaml
@@ -1,30 +1,50 @@
-name: Format code
+name: Check and Format Code
 
 on:
   push:
     branches:
       - '**'
+  pull_request:
 
 jobs:
-  format:
+  check-black:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
+          python-version: '3.9'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install black
+      - name: Check if black has been run
+        id: check
+        run: |
+          black --check src || echo "Black check failed" && exit 1
+
+  format:
+    runs-on: ubuntu-latest
+    needs: check-black
+    if: failure()
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
           python-version: '3.12'
+      - name: Install dependencies
+        run: |
+          pip install black isort autoflake
       - name: Format code with black
         run: |
-          pip install black
           black --include="\.py" src
       - name: Sort imports with isort
         run: |
-          pip install isort
           isort src
       - name: Remove unused imports with autoflake
         run: |
-          pip install autoflake
           autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive src
       - name: Commit changes
         uses: EndBug/add-and-commit@v9
@@ -34,3 +54,21 @@ jobs:
           message: "Automatic code formatting with black, sort imports with isort, and remove unused imports with autoflake"
           add: "."
           github_token: ${{ secrets.GITHUB_TOKEN }}
+
+  recheck-black:
+    runs-on: ubuntu-latest
+    needs: format
+    if: always()
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.9'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install black
+      - name: Re-check if black has been run
+        run: |
+          black --check src
