adding status checks

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -7,11 +7,19 @@ jobs:
         steps:
             - name: Step 1
               run: sleep 20
+            - name: Step 2
+              # We can give a step an id to reference it later
+              id: step2
+              run: exit 1
+              # This will run if the step with id step2 fails
+            - name: Runs on Step 2 Failure
+              if: steps.step2.conclusion == 'failure'
+              run: echo "Step 2 failed"
             - name: Force Fail
               run: exit 1
             - name: Runs on Failure
-              if: failure()
-              run: echo "This job failed"
+              if: failure() && steps.step2.conclusion == 'failure'
+              run: echo "This job is a complete failure"
               # This is not really needed because it is the default behavior
             - name: Runs on Success
               if: success()
